### ISSUE TITLE
Impossibile collegare Trakt

### ISSUE THREAD

**Issue by EffeF** [Stream4me/addon#153]
Dopo aver attivato la relativa opzione nelle impostazioni di KoD appare il codice da inserire su Trakt, ma una volta fatto ciò il popup con le istruzioni non si chiude, ed il collegamento a Trakt non viene effettuato. 

KoD:  v0.5
Kodi: 18.5

**Comment by mac12m99** [comment]
Ciao,
grazie della segnalazione, appena posso do' un occhiata :)

**Comment by Alhaziel01** [comment]
Ciao EffeF, il problema con Trakt dovrebbe essere stato risolto, potresti provare e darci conferma?

**Comment by EffeF** [comment]
No, anche con la v0.5.2 continua a rimanere piantato sulla schermata con il codice chiedendo di attendere.

**Comment by EffeF** [comment]
> No, anche con la v0.5.2 continua a rimanere piantato sulla schermata con il codice chiedendo di attendere.

Devo rettificare, a quanto pare, su Windows, solo sulla versione UWP scaricabile dallo store Microsoft continua a non funzionarmi, sulla normale versione .exe invece confermo che il problema è stato risolto.

**Comment by Alhaziel01** [comment]
@EffeF grazie dell'informazione, proveremo a controllare anche la versione dello store.

**Comment by EffeF** [comment]
Non capisco perché l'altro giorno abbia funzionanti, ma direi che in realtà il problema con Trakt non è risolto.

Ho dovuto installare KoD ex novo su una installazione pulita di Kodi, ed ancora una volta resta piantato sulla schermata con il codice Trakt. Perciò al momento non mi funziona ne su Windows (sia .exe che UWP), ne su Android TV, unici OS su cui ho potuto testarlo.

In tutti i casi il log mostra il seguente errore, con l'ultima parte che si ripete all'infinito dal momento in cui inserisco il codice sul sito di Trakt a quando chiudo la finestra di KoD annullando:
```
2019-12-22 22:50:13.552 T:5256   ERROR: ######## ERROR #########
2019-12-22 22:50:13.552 T:5256   ERROR:     [kod.core.trakt_tools.auth_trakt] Traceback (most recent call last):
                                              File "C:\Users\EffeF\AppData\Roaming\Kodi\addons\plugin.video.kod\core\trakt_tools.py", line 29, in auth_trakt
                                                item.verify_url = data["verification_url"]
                                            KeyError: 'verification_url'
2019-12-22 22:50:24.247 T:4708 WARNING: Invalid media type "list"
2019-12-22 22:50:28.242 T:1576 WARNING: Previous line repeats 22 times.
2019-12-22 22:50:28.242 T:1576   ERROR: ######## ERROR #########
2019-12-22 22:50:28.242 T:1576   ERROR:     [kod.core.filetools.read] ERROR al leer el archivo: C:\Users\EffeF\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.kod\settings_channels\autoplay_data.json
2019-12-22 22:50:28.243 T:1576   ERROR: ######## ERROR #########
2019-12-22 22:50:28.243 T:1576   ERROR:     [kod.core.filetools.read] Traceback (most recent call last):
                                              File "C:\Users\EffeF\AppData\Roaming\Kodi\addons\plugin.video.kod\core\filetools.py", line 112, in read
                                                f = open(path, "rb")
                                            IOError: [Errno 2] No such file or directory: u'C:\\Users\\EffeF\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\plugin.video.kod\\settings_channels\\autoplay_data.json'
2019-12-22 22:50:28.244 T:1576   ERROR: ######## ERROR #########
2019-12-22 22:50:28.244 T:1576   ERROR:     [kod.core.jsontools.load] **NO** se ha podido cargar el JSON
2019-12-22 22:50:28.249 T:1576   ERROR: ######## ERROR #########
2019-12-22 22:50:28.249 T:1576   ERROR:     [kod.core.jsontools.load] Traceback (most recent call last):
                                              File "C:\Users\EffeF\AppData\Roaming\Kodi\addons\plugin.video.kod\core\jsontools.py", line 38, in load
                                                value = json.loads(*args, **kwargs)
                                              File "C:\Program Files\Kodi\system\python\Lib\json\__init__.py", line 352, in loads
                                                return cls(encoding=encoding, **kw).decode(s)
                                              File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 364, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                            TypeError: expected string or buffer
2019-12-22 22:50:35.316 T:1576   ERROR: ######## ERROR #########
2019-12-22 22:50:35.316 T:1576   ERROR:     [kod.core.jsontools.load] **NO** se ha podido cargar el JSON
2019-12-22 22:50:35.317 T:1576   ERROR: ######## ERROR #########
2019-12-22 22:50:35.317 T:1576   ERROR:     [kod.core.jsontools.load] Traceback (most recent call last):
                                              File "C:\Users\EffeF\AppData\Roaming\Kodi\addons\plugin.video.kod\core\jsontools.py", line 38, in load
                                                value = json.loads(*args, **kwargs)
                                              File "C:\Program Files\Kodi\system\python\Lib\json\__init__.py", line 352, in loads
                                                return cls(encoding=encoding, **kw).decode(s)
                                              File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 364, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 382, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
2019-12-22 22:50:41.147 T:1576   ERROR: ######## ERROR #########
2019-12-22 22:50:41.147 T:1576   ERROR:     [kod.core.jsontools.load] **NO** se ha podido cargar el JSON
2019-12-22 22:50:41.148 T:1576   ERROR: ######## ERROR #########
2019-12-22 22:50:41.148 T:1576   ERROR:     [kod.core.jsontools.load] Traceback (most recent call last):
                                              File "C:\Users\EffeF\AppData\Roaming\Kodi\addons\plugin.video.kod\core\jsontools.py", line 38, in load
                                                value = json.loads(*args, **kwargs)
                                              File "C:\Program Files\Kodi\system\python\Lib\json\__init__.py", line 352, in loads
                                                return cls(encoding=encoding, **kw).decode(s)
                                              File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 364, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 382, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
```

**Comment by mac12m99** [comment]
Ciao,
purtroppo è passato molto tempo e trakt è passato nel dimenticatoio in favore di altre feature più urgenti, potresti gentilmente riprovare e dirmi se il problema persiste ancora?
