### ISSUE TITLE
La versione beta non funziona più completamente 

### ISSUE THREAD

**Issue by xXTimmy89Xx** [Stream4me/addon#159]
@mac12m99 Dopo la pulizia generale di KOD ca57cfa la versione beta di KOD ha smesso di funzionare completamente, volevo sapere se è una cosa voluta.

2019-12-28 00:05:57.422 T:10252   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named certifi
                                            Traceback (most recent call last):
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\default.py", line 23, in <module>
                                                launcher.start()
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\platformcode\launcher.py", line 38, in start
                                                from specials import resolverdns
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\specials\resolverdns.py", line 8, in <module>
                                                from lib.requests_toolbelt.adapters import host_header_ssl
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\lib\requests_toolbelt\__init__.py", line 12, in <module>
                                                from .adapters import SSLAdapter, SourceAddressAdapter
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\lib\requests_toolbelt\adapters\__init__.py", line 12, in <module>
                                                from .ssl import SSLAdapter
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\lib\requests_toolbelt\adapters\ssl.py", line 12, in <module>
                                                import requests
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\lib\requests\__init__.py", line 112, in <module>
                                                from . import utils
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\lib\requests\utils.py", line 24, in <module>
                                                from . import certs
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\lib\requests\certs.py", line 15, in <module>
                                                from certifi import where
                                            ImportError: No module named certifi
                                            -->End of Python script error report<--
2019-12-28 00:05:57.432 T:9252   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.kod/
2019-12-28 00:05:57.432 T:13892   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.kod/) failed

**Comment by mac12m99** [comment]
@Timmy89ITA Nel fare la pulizia devo aver cancellato qualcosa che in realtà era usato davvero.. domani sistemo
D'altronde la beta è il ramo di sviluppo, capita spesso che rompiamo tutto 😂
Grazie di averlo segnalato👍

**Comment by xXTimmy89Xx** [comment]
@mac12m99 hahaha tranquillo può capitare anzi grazie a tutti voi per il lavoro svolto nonostante questi giorni di festa! buone feste!!!

**Comment by mac12m99** [comment]
Ora dovrebbe essere risolto :)
