### ISSUE TITLE
Siti di hosting video mancanti

### ISSUE THREAD

**Issue by xXTimmy89Xx** [Stream4me/addon#167]
Dopo gli ultimi aggiornamenti della versione beta di kod alcuni siti di hosting video 4k e non, sono spariti, Altadefinizione.click è uno dei pochi siti dove sono presenti anche se pochi film in 4k e in italino ed è possibile trovarli su kod andando nel canale Altadefinizione.click/qualità/4k, dopo gli ultimi aggiornamenti purtroppo sono spariti assieme ad altri siti di hosting.

Prima dell'aggiornamento
![screenshot000](https://user-images.githubusercontent.com/53865707/72130749-afff6b00-337a-11ea-810b-4d2bf4e620a6.png)

Dopo l'aggiornamento
![screenshot001](https://user-images.githubusercontent.com/53865707/72130754-b5f54c00-337a-11ea-8a75-e49eaa8e5d39.png)

Il problema sembra non presentarsi nella versione stabile.

2020-01-10 13:30:28.553 T:6535   ERROR: NEWADDON Unknown Video Info Key "quality"
2020-01-10 13:30:59.139 T:6551   ERROR: Previous line repeats 23 times.
2020-01-10 13:30:59.139 T:6551   ERROR: ######## ERROR #########
2020-01-10 13:30:59.139 T:6551   ERROR:     [kod.specials.resolverdns.getIp] Failed to resolve hostname, fallback to normal dns
2020-01-10 13:30:59.140 T:6551   ERROR: Traceback (most recent call last):
2020-01-10 13:30:59.141 T:6551   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kod/specials/resolverdns.py", line 62, in getIp
2020-01-10 13:30:59.141 T:6551   ERROR:     ip = doh.query(domain)[0]
2020-01-10 13:30:59.142 T:6551   ERROR: IndexError: list index out of range
2020-01-10 13:30:59.142 T:6551   ERROR: ######## ERROR #########
2020-01-10 13:30:59.143 T:6551   ERROR:     [kod.specials.resolverdns.getIp] None
2020-01-10 13:31:20.530 T:6551   ERROR: ######## ERROR #########
2020-01-10 13:31:20.530 T:6551   ERROR:     [kod.specials.resolverdns.getIp] Failed to resolve hostname, fallback to normal dns
2020-01-10 13:31:20.530 T:6551   ERROR: Traceback (most recent call last):
2020-01-10 13:31:20.530 T:6551   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kod/specials/resolverdns.py", line 62, in getIp
2020-01-10 13:31:20.531 T:6551   ERROR:     ip = doh.query(domain)[0]
2020-01-10 13:31:20.531 T:6551   ERROR: IndexError: list index out of range
2020-01-10 13:31:20.532 T:6551   ERROR: ######## ERROR #########
2020-01-10 13:31:20.532 T:6551   ERROR:     [kod.specials.resolverdns.getIp] None
2020-01-10 13:31:29.826 T:6551   ERROR: ######## ERROR #########
2020-01-10 13:31:29.826 T:6551   ERROR:     [kod.specials.resolverdns.getIp] Failed to resolve hostname, fallback to normal dns
2020-01-10 13:31:29.826 T:6551   ERROR: Traceback (most recent call last):
2020-01-10 13:31:29.827 T:6551   ERROR:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kod/specials/resolverdns.py", line 62, in getIp
2020-01-10 13:31:29.827 T:6551   ERROR:     ip = doh.query(domain)[0]
2020-01-10 13:31:29.827 T:6551   ERROR: IndexError: list index out of range
2020-01-10 13:31:29.828 T:6551   ERROR: ######## ERROR #########
2020-01-10 13:31:29.829 T:6551   ERROR:     [kod.specials.resolverdns.getIp] None
2020-01-10 13:31:31.853 T:6551   ERROR: NEWADDON Unknown Video Info Key "quality"
2020-01-10 13:31:31.853 T:6551   ERROR: NEWADDON Unknown Video Info Key "thumbnail"
2020-01-10 13:31:31.953 T:6551   ERROR: NEWADDON Unknown Video Info Key "quality"
2020-01-10 13:31:31.953 T:6551   ERROR: NEWADDON Unknown Video Info Key "thumbnail"
2020-01-10 13:31:32.003 T:6551   ERROR: NEWADDON Unknown Video Info Key "quality"
2020-01-10 13:31:32.003 T:6551   ERROR: NEWADDON Unknown Video Info Key "thumbnail"
2020-01-10 13:31:32.040 T:6551   ERROR: NEWADDON Unknown Video Info Key "quality"
2020-01-10 13:31:32.041 T:6551   ERROR: NEWADDON Unknown Video Info Key "thumbnail"
2020-01-10 13:31:32.092 T:6551   ERROR: NEWADDON Unknown Video Info Key "quality"
2020-01-10 13:31:32.092 T:6551   ERROR: NEWADDON Unknown Video Info Key "thumbnail"
2020-01-10 13:31:32.140 T:6551   ERROR: NEWADDON Unknown Video Info Key "quality"
2020-01-10 13:31:32.141 T:6551   ERROR: NEWADDON Unknown Video Info Key "thumbnail"
2020-01-10 13:32:20.053 T:6604   ERROR: NEWADDON Unknown Video Info Key "quality"
2020-01-10 13:32:20.053 T:6604   ERROR: NEWADDON Unknown Video Info Key "thumbnail"
2020-01-10 13:32:20.153 T:6604   ERROR: NEWADDON Unknown Video Info Key "quality"
2020-01-10 13:32:20.153 T:6604   ERROR: NEWADDON Unknown Video Info Key "thumbnail"
2020-01-10 13:32:20.253 T:6604   ERROR: NEWADDON Unknown Video Info Key "quality"
2020-01-10 13:32:20.253 T:6604   ERROR: NEWADDON Unknown Video Info Key "thumbnail"

**Comment by mac12m99** [comment]
Risolto con 6ab5e3db797f2b1dd01a33c441ff64c5287f004f
Grazie!
