### ISSUE TITLE
Sezione Film/Serie tv, Ultimi aggiornati/e e Ultimi aggiunti/e di vari canali non funzionante.

### ISSUE THREAD

**Issue by xXTimmy89Xx** [Stream4me/addon#175]
Dopo gli ultimi aggiornamenti nella versione beta le sezioni Film/Serie tv, Ultimi aggiornati/e e Ultimi aggiunti/e di vari canali sembra aver smesso di funzionare correttamente restituendo un errore.

2020-01-20 21:15:37.070 T:14044   ERROR: ######## ERROR #########
2020-01-20 21:15:37.070 T:14044   ERROR:     [kod.platformcode.launcher.run] Traceback (most recent call last):
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\platformcode\launcher.py", line 295, in run
                                                itemlist = getattr(channel, item.action)(item)
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\core\support.py", line 418, in wrapper
                                                typeActionDict, blacklist, search, pag, function, lang)
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\core\support.py", line 234, in scrapeBlock
                                                title = cleantitle(scraped['title']) if scraped['title'] else ''
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\core\support.py", line 171, in cleantitle
                                                cleantitle = scrapertools.htmlclean(scrapertools.decodeHtmlentities(title).replace('"', "'").replace('×', 'x').replace('–', '-')).strip()
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
2020-01-20 21:15:38.715 T:14080   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.kod/?ewogICAgImFjdGlvbiI6ICJwZWxpY3VsYXMiLCAKICAgICJhcmdzIjogW10sIAogICAgImNhdGVnb3J5IjogIkNCMDEiLCAKICAgICJjaGFubmVsIjogImNpbmVibG9nMDEiLCAKICAgICJleHRyYSI6ICJtb3ZpZSIsIAogICAgImZhbmFydCI6ICIiLCAKICAgICJpbmZvTGFiZWxzIjogewogICAgICAgICJtZWRpYXR5cGUiOiAibW92aWUiCiAgICB9LCAKICAgICJ0aHVtYm5haWwiOiAiaHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL2tvZGlvbmRlbWFuZC9tZWRpYS9tYXN0ZXIvdGhlbWVzL2RlZmF1bHQvdGh1bWJfY2hhbm5lbHNfbW92aWUucG5nIiwgCiAgICAidGl0bGUiOiAiW0Jd4oCiWy9CXSBbQl1GaWxtWy9CXSIsIAogICAgInRvdGFsSXRlbXMiOiAwLCAKICAgICJ1cmwiOiAiaHR0cHM6Ly9jYjAxLmlyaXNoLyIsIAogICAgIndhbnRlZCI6ICIiCn0%3d
2020-01-20 21:15:38.718 T:8888   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.kod/?ewogICAgImFjdGlvbiI6ICJwZWxpY3VsYXMiLCAKICAgICJhcmdzIjogW10sIAogICAgImNhdGVnb3J5IjogIkNCMDEiLCAKICAgICJjaGFubmVsIjogImNpbmVibG9nMDEiLCAKICAgICJleHRyYSI6ICJtb3ZpZSIsIAogICAgImZhbmFydCI6ICIiLCAKICAgICJpbmZvTGFiZWxzIjogewogICAgICAgICJtZWRpYXR5cGUiOiAibW92aWUiCiAgICB9LCAKICAgICJ0aHVtYm5haWwiOiAiaHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL2tvZGlvbmRlbWFuZC9tZWRpYS9tYXN0ZXIvdGhlbWVzL2RlZmF1bHQvdGh1bWJfY2hhbm5lbHNfbW92aWUucG5nIiwgCiAgICAidGl0bGUiOiAiW0Jd4oCiWy9CXSBbQl1GaWxtWy9CXSIsIAogICAgInRvdGFsSXRlbXMiOiAwLCAKICAgICJ1cmwiOiAiaHR0cHM6Ly9jYjAxLmlyaXNoLyIsIAogICAgIndhbnRlZCI6ICIiCn0%3d) failed
2020-01-20 21:15:38.947 T:13504 WARNING: Invalid media type "list"
2020-01-20 21:15:43.671 T:5000   ERROR: ######## ERROR #########
2020-01-20 21:15:43.671 T:5000   ERROR:     [kod.platformcode.launcher.run] Traceback (most recent call last):
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\platformcode\launcher.py", line 295, in run
                                                itemlist = getattr(channel, item.action)(item)
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\core\support.py", line 407, in wrapper
                                                typeContentDict, typeActionDict, blacklist, search, pag, function, lang)
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\core\support.py", line 234, in scrapeBlock
                                                title = cleantitle(scraped['title']) if scraped['title'] else ''
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\core\support.py", line 171, in cleantitle
                                                cleantitle = scrapertools.htmlclean(scrapertools.decodeHtmlentities(title).replace('"', "'").replace('×', 'x').replace('–', '-')).strip()
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
2020-01-20 21:15:45.186 T:5316   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.kod/?ewogICAgImFjdGlvbiI6ICJwZWxpY3VsYXMiLCAKICAgICJhcmdzIjogIm5ld2VzdCIsIAogICAgImNhdGVnb3J5IjogIkNCMDEiLCAKICAgICJjaGFubmVsIjogImNpbmVibG9nMDEiLCAKICAgICJleHRyYSI6ICJtb3ZpZSIsIAogICAgImZhbmFydCI6ICIiLCAKICAgICJpbmZvTGFiZWxzIjogewogICAgICAgICJtZWRpYXR5cGUiOiAibW92aWUiCiAgICB9LCAKICAgICJ0aHVtYm5haWwiOiAiaHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL2tvZGlvbmRlbWFuZC9tZWRpYS9tYXN0ZXIvdGhlbWVzL2RlZmF1bHQvdGh1bWJfY2hhbm5lbHNfbW92aWUucG5nIiwgCiAgICAidGl0bGUiOiAi4oCi4oCiIFVsdGltaSBBZ2dpb3JuYXRpIiwgCiAgICAidG90YWxJdGVtcyI6IDAsIAogICAgInVybCI6ICJodHRwczovL2NiMDEuaXJpc2gvL2xpc3RhLWZpbG0tdWx0aW1pLTEwMC1maWxtLWFnZ2lvcm5hdGkvIiwgCiAgICAid2FudGVkIjogIiIKfQ%3d%3d
2020-01-20 21:15:45.197 T:8888   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.kod/?ewogICAgImFjdGlvbiI6ICJwZWxpY3VsYXMiLCAKICAgICJhcmdzIjogIm5ld2VzdCIsIAogICAgImNhdGVnb3J5IjogIkNCMDEiLCAKICAgICJjaGFubmVsIjogImNpbmVibG9nMDEiLCAKICAgICJleHRyYSI6ICJtb3ZpZSIsIAogICAgImZhbmFydCI6ICIiLCAKICAgICJpbmZvTGFiZWxzIjogewogICAgICAgICJtZWRpYXR5cGUiOiAibW92aWUiCiAgICB9LCAKICAgICJ0aHVtYm5haWwiOiAiaHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL2tvZGlvbmRlbWFuZC9tZWRpYS9tYXN0ZXIvdGhlbWVzL2RlZmF1bHQvdGh1bWJfY2hhbm5lbHNfbW92aWUucG5nIiwgCiAgICAidGl0bGUiOiAi4oCi4oCiIFVsdGltaSBBZ2dpb3JuYXRpIiwgCiAgICAidG90YWxJdGVtcyI6IDAsIAogICAgInVybCI6ICJodHRwczovL2NiMDEuaXJpc2gvL2xpc3RhLWZpbG0tdWx0aW1pLTEwMC1maWxtLWFnZ2lvcm5hdGkvIiwgCiAgICAid2FudGVkIjogIiIKfQ%3d%3d) failed
2020-01-20 21:15:45.408 T:14812 WARNING: Invalid media type "list"
2020-01-20 21:15:46.224 T:12180   ERROR: ######## ERROR #########
2020-01-20 21:15:46.224 T:12180   ERROR:     [kod.platformcode.launcher.run] Traceback (most recent call last):
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\platformcode\launcher.py", line 295, in run
                                                itemlist = getattr(channel, item.action)(item)
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\core\support.py", line 407, in wrapper
                                                typeContentDict, typeActionDict, blacklist, search, pag, function, lang)
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\core\support.py", line 234, in scrapeBlock
                                                title = cleantitle(scraped['title']) if scraped['title'] else ''
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\core\support.py", line 171, in cleantitle
                                                cleantitle = scrapertools.htmlclean(scrapertools.decodeHtmlentities(title).replace('"', "'").replace('×', 'x').replace('–', '-')).strip()
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
2020-01-20 21:15:47.454 T:11432   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.kod/?ewogICAgImFjdGlvbiI6ICJwZWxpY3VsYXMiLCAKICAgICJhcmdzIjogIm5ld2VzdCIsIAogICAgImNhdGVnb3J5IjogIkNCMDEiLCAKICAgICJjaGFubmVsIjogImNpbmVibG9nMDEiLCAKICAgICJleHRyYSI6ICJtb3ZpZSIsIAogICAgImZhbmFydCI6ICIiLCAKICAgICJpbmZvTGFiZWxzIjogewogICAgICAgICJtZWRpYXR5cGUiOiAibW92aWUiCiAgICB9LCAKICAgICJ0aHVtYm5haWwiOiAiaHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL2tvZGlvbmRlbWFuZC9tZWRpYS9tYXN0ZXIvdGhlbWVzL2RlZmF1bHQvdGh1bWJfY2hhbm5lbHNfbW92aWUucG5nIiwgCiAgICAidGl0bGUiOiAi4oCi4oCiIFVsdGltaSBBZ2dpdW50aSIsIAogICAgInRvdGFsSXRlbXMiOiAwLCAKICAgICJ1cmwiOiAiaHR0cHM6Ly9jYjAxLmlyaXNoLy9saXN0YS1maWxtLXVsdGltaS0xMDAtZmlsbS1hZ2dpdW50aS8iLCAKICAgICJ3YW50ZWQiOiAiIgp9
2020-01-20 21:15:47.464 T:8888   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.kod/?ewogICAgImFjdGlvbiI6ICJwZWxpY3VsYXMiLCAKICAgICJhcmdzIjogIm5ld2VzdCIsIAogICAgImNhdGVnb3J5IjogIkNCMDEiLCAKICAgICJjaGFubmVsIjogImNpbmVibG9nMDEiLCAKICAgICJleHRyYSI6ICJtb3ZpZSIsIAogICAgImZhbmFydCI6ICIiLCAKICAgICJpbmZvTGFiZWxzIjogewogICAgICAgICJtZWRpYXR5cGUiOiAibW92aWUiCiAgICB9LCAKICAgICJ0aHVtYm5haWwiOiAiaHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL2tvZGlvbmRlbWFuZC9tZWRpYS9tYXN0ZXIvdGhlbWVzL2RlZmF1bHQvdGh1bWJfY2hhbm5lbHNfbW92aWUucG5nIiwgCiAgICAidGl0bGUiOiAi4oCi4oCiIFVsdGltaSBBZ2dpdW50aSIsIAogICAgInRvdGFsSXRlbXMiOiAwLCAKICAgICJ1cmwiOiAiaHR0cHM6Ly9jYjAxLmlyaXNoLy9saXN0YS1maWxtLXVsdGltaS0xMDAtZmlsbS1hZ2dpdW50aS8iLCAKICAgICJ3YW50ZWQiOiAiIgp9) failed
2020-01-20 21:15:47.679 T:15524 WARNING: Invalid media type "list"
2020-01-20 21:15:53.330 T:8888 WARNING: CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2020-01-20 21:15:53.468 T:9096 WARNING: Previous line repeats 6 times.
2020-01-20 21:15:53.468 T:9096   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.kod/?ewogICAgImFjdGlvbiI6ICJzZWFyY2giLCAKICAgICJhcmdzIjogW10sIAogICAgImNhdGVnb3J5IjogIkNCMDEiLCAKICAgICJjaGFubmVsIjogImNpbmVibG9nMDEiLCAKICAgICJleHRyYSI6ICJ0dnNob3ciLCAKICAgICJmYW5hcnQiOiAiIiwgCiAgICAiaW5mb0xhYmVscyI6IHsKICAgICAgICAibWVkaWF0eXBlIjogInR2c2hvdyIKICAgIH0sIAogICAgInRodW1ibmFpbCI6ICJodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20va29kaW9uZGVtYW5kL21lZGlhL21hc3Rlci90aGVtZXMvZGVmYXVsdC90aHVtYl9zZWFyY2hfdHZzaG93LnBuZyIsIAogICAgInRpdGxlIjogIltCXeKAouKAoiBDZXJjYSBTZXJpZSBUViDigKZbL0JdIiwgCiAgICAidG90YWxJdGVtcyI6IDAsIAogICAgInVybCI6ICJodHRwczovL2NiMDEuaXJpc2gvL3NlcmlldHYvIiwgCiAgICAid2FudGVkIjogIiIKfQ%3d%3d
2020-01-20 21:15:53.478 T:8888   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.kod/?ewogICAgImFjdGlvbiI6ICJzZWFyY2giLCAKICAgICJhcmdzIjogW10sIAogICAgImNhdGVnb3J5IjogIkNCMDEiLCAKICAgICJjaGFubmVsIjogImNpbmVibG9nMDEiLCAKICAgICJleHRyYSI6ICJ0dnNob3ciLCAKICAgICJmYW5hcnQiOiAiIiwgCiAgICAiaW5mb0xhYmVscyI6IHsKICAgICAgICAibWVkaWF0eXBlIjogInR2c2hvdyIKICAgIH0sIAogICAgInRodW1ibmFpbCI6ICJodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20va29kaW9uZGVtYW5kL21lZGlhL21hc3Rlci90aGVtZXMvZGVmYXVsdC90aHVtYl9zZWFyY2hfdHZzaG93LnBuZyIsIAogICAgInRpdGxlIjogIltCXeKAouKAoiBDZXJjYSBTZXJpZSBUViDigKZbL0JdIiwgCiAgICAidG90YWxJdGVtcyI6IDAsIAogICAgInVybCI6ICJodHRwczovL2NiMDEuaXJpc2gvL3NlcmlldHYvIiwgCiAgICAid2FudGVkIjogIiIKfQ%3d%3d) failed
2020-01-20 21:15:53.702 T:14540 WARNING: Invalid media type "list"
2020-01-20 21:15:56.791 T:13004   ERROR: ######## ERROR #########
2020-01-20 21:15:56.791 T:13004   ERROR:     [kod.platformcode.launcher.run] Traceback (most recent call last):
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\platformcode\launcher.py", line 295, in run
                                                itemlist = getattr(channel, item.action)(item)
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\core\support.py", line 407, in wrapper
                                                typeContentDict, typeActionDict, blacklist, search, pag, function, lang)
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\core\support.py", line 238, in scrapeBlock
                                                plot = cleantitle(scraped["plot"]) if scraped["plot"] else ''
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\core\support.py", line 171, in cleantitle
                                                cleantitle = scrapertools.htmlclean(scrapertools.decodeHtmlentities(title).replace('"', "'").replace('×', 'x').replace('–', '-')).strip()
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
2020-01-20 21:15:58.043 T:7716   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.kod/?ewogICAgImFjdGlvbiI6ICJwZWxpY3VsYXMiLCAKICAgICJhcmdzIjogIm5ld2VzdCIsIAogICAgImNhdGVnb3J5IjogIkNCMDEiLCAKICAgICJjaGFubmVsIjogImNpbmVibG9nMDEiLCAKICAgICJleHRyYSI6ICJ0dnNob3ciLCAKICAgICJmYW5hcnQiOiAiIiwgCiAgICAiaW5mb0xhYmVscyI6IHsKICAgICAgICAibWVkaWF0eXBlIjogInR2c2hvdyIKICAgIH0sIAogICAgInRodW1ibmFpbCI6ICJodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20va29kaW9uZGVtYW5kL21lZGlhL21hc3Rlci90aGVtZXMvZGVmYXVsdC90aHVtYl9jaGFubmVsc190dnNob3cucG5nIiwgCiAgICAidGl0bGUiOiAi4oCi4oCiIFVsdGltZSBBZ2dpb3JuYXRlIiwgCiAgICAidG90YWxJdGVtcyI6IDAsIAogICAgInVybCI6ICJodHRwczovL2NiMDEuaXJpc2gvL3NlcmlldHYvIiwgCiAgICAid2FudGVkIjogIiIKfQ%3d%3d
2020-01-20 21:15:58.052 T:8888   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.kod/?ewogICAgImFjdGlvbiI6ICJwZWxpY3VsYXMiLCAKICAgICJhcmdzIjogIm5ld2VzdCIsIAogICAgImNhdGVnb3J5IjogIkNCMDEiLCAKICAgICJjaGFubmVsIjogImNpbmVibG9nMDEiLCAKICAgICJleHRyYSI6ICJ0dnNob3ciLCAKICAgICJmYW5hcnQiOiAiIiwgCiAgICAiaW5mb0xhYmVscyI6IHsKICAgICAgICAibWVkaWF0eXBlIjogInR2c2hvdyIKICAgIH0sIAogICAgInRodW1ibmFpbCI6ICJodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20va29kaW9uZGVtYW5kL21lZGlhL21hc3Rlci90aGVtZXMvZGVmYXVsdC90aHVtYl9jaGFubmVsc190dnNob3cucG5nIiwgCiAgICAidGl0bGUiOiAi4oCi4oCiIFVsdGltZSBBZ2dpb3JuYXRlIiwgCiAgICAidG90YWxJdGVtcyI6IDAsIAogICAgInVybCI6ICJodHRwczovL2NiMDEuaXJpc2gvL3NlcmlldHYvIiwgCiAgICAid2FudGVkIjogIiIKfQ%3d%3d) failed
2020-01-20 21:15:58.305 T:12376 WARNING: Invalid media type "list"
2020-01-20 21:15:58.309 T:8240   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.kod/?ewogICAgImFjdGlvbiI6ICJtYWlubGlzdCIsIAogICAgImNhdGVnb3J5IjogIkNCMDEiLCAKICAgICJjaGFubmVsIjogImNpbmVibG9nMDEiLCAKICAgICJjb250ZXh0IjogWwogICAgICAgIHsKICAgICAgICAgICAgImFjdGlvbiI6ICJjaGFubmVsX2NvbmZpZyIsIAogICAgICAgICAgICAiY2hhbm5lbCI6ICJzZXR0aW5nIiwgCiAgICAgICAgICAgICJjb25maWciOiAiY2luZWJsb2cwMSIsIAogICAgICAgICAgICAiZnJvbV9hY3Rpb24iOiAibWFpbmxpc3QiLCAKICAgICAgICAgICAgImZyb21fY2hhbm5lbCI6ICJjaW5lYmxvZzAxIiwgCiAgICAgICAgICAgICJ0aXRsZSI6ICJDb25maWd1cmEgY2FuYWxlIgogICAgICAgIH0KICAgIF0sIAogICAgImZhbmFydCI6ICIiLCAKICAgICJpbmZvTGFiZWxzIjogewogICAgICAgICJtZWRpYXR5cGUiOiAibGlzdCIsIAogICAgICAgICJwbG90IjogIltCXVRpcG8gZGkgY29udGVudXRvOiBbL0JdU2VyaWUgVFYsIEZpbG0sIFZlcnNpb25lIE9yaWdpbmFsZSwgRG9jdW1lbnRhcmlcblxuW0JdTGluZ3VlIFsvQl0gSXRhbGlhbm8sIFNvdHRvdGl0b2xhdG8gaW4gSXRhbGlhbm8iCiAgICB9LCAKICAgICJsYW5ndWFnZSI6IFsKICAgICAgICAiaXRhIiwgCiAgICAgICAgInN1Yi1pdGEiCiAgICBdLCAKICAgICJ0aHVtYm5haWwiOiAiaHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL2tvZGlvbmRlbWFuZC9tZWRpYS9tYXN0ZXIvcmVzb3VyY2VzXFx0aHVtYlxcY2IwMS5wbmciLCAKICAgICJ0aXRsZSI6ICJDQjAxIiwgCiAgICAidG90YWxJdGVtcyI6IDAsIAogICAgInZpZXdtb2RlIjogImxpc3QiCn0%3d
2020-01-20 21:15:58.317 T:8888   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.kod/?ewogICAgImFjdGlvbiI6ICJtYWlubGlzdCIsIAogICAgImNhdGVnb3J5IjogIkNCMDEiLCAKICAgICJjaGFubmVsIjogImNpbmVibG9nMDEiLCAKICAgICJjb250ZXh0IjogWwogICAgICAgIHsKICAgICAgICAgICAgImFjdGlvbiI6ICJjaGFubmVsX2NvbmZpZyIsIAogICAgICAgICAgICAiY2hhbm5lbCI6ICJzZXR0aW5nIiwgCiAgICAgICAgICAgICJjb25maWciOiAiY2luZWJsb2cwMSIsIAogICAgICAgICAgICAiZnJvbV9hY3Rpb24iOiAibWFpbmxpc3QiLCAKICAgICAgICAgICAgImZyb21fY2hhbm5lbCI6ICJjaW5lYmxvZzAxIiwgCiAgICAgICAgICAgICJ0aXRsZSI6ICJDb25maWd1cmEgY2FuYWxlIgogICAgICAgIH0KICAgIF0sIAogICAgImZhbmFydCI6ICIiLCAKICAgICJpbmZvTGFiZWxzIjogewogICAgICAgICJtZWRpYXR5cGUiOiAibGlzdCIsIAogICAgICAgICJwbG90IjogIltCXVRpcG8gZGkgY29udGVudXRvOiBbL0JdU2VyaWUgVFYsIEZpbG0sIFZlcnNpb25lIE9yaWdpbmFsZSwgRG9jdW1lbnRhcmlcblxuW0JdTGluZ3VlIFsvQl0gSXRhbGlhbm8sIFNvdHRvdGl0b2xhdG8gaW4gSXRhbGlhbm8iCiAgICB9LCAKICAgICJsYW5ndWFnZSI6IFsKICAgICAgICAiaXRhIiwgCiAgICAgICAgInN1Yi1pdGEiCiAgICBdLCAKICAgICJ0aHVtYm5haWwiOiAiaHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL2tvZGlvbmRlbWFuZC9tZWRpYS9tYXN0ZXIvcmVzb3VyY2VzXFx0aHVtYlxcY2IwMS5wbmciLCAKICAgICJ0aXRsZSI6ICJDQjAxIiwgCiAgICAidG90YWxJdGVtcyI6IDAsIAogICAgInZpZXdtb2RlIjogImxpc3QiCn0%3d) failed

![screenshot000](https://user-images.githubusercontent.com/53865707/72756496-ae7d4080-3bcd-11ea-98b3-72785ddd522b.png)

**Comment by xXTimmy89Xx** [comment]
Corretto con c785e5a
