### ISSUE TITLE
Adesso in onda/[Oggi in TV] Film

### ISSUE THREAD

**Issue by xXTimmy89Xx** [Stream4me/addon#176]
Dopo gli ultimi aggiornamenti nella versione beta la sezione Adesso in onda/[Oggi in TV] Film ha smesso di funzionare correttamente e restituisce un errore.

2020-01-21 08:16:24.094 T:15164   ERROR: ######## ERROR #########
2020-01-21 08:16:24.094 T:15164   ERROR:     [kod.platformcode.launcher.run] Traceback (most recent call last):
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\platformcode\launcher.py", line 295, in run
                                                itemlist = getattr(channel, item.action)(item)
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\specials\filmontv.py", line 169, in now_on_tv
                                                scrapedtitle = scrapertools.decodeHtmlentities(scrapedtitle).strip()
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\core\scrapertools.py", line 44, in decodeHtmlentities
                                                return unicode(parser.unescape(data))
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 13: ordinal not in range(128)
2020-01-21 08:16:25.784 T:7628 WARNING: CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2020-01-21 08:16:25.924 T:8832 WARNING: Previous line repeats 8 times.
2020-01-21 08:16:25.924 T:8832   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.kod/?ewogICAgImFjdGlvbiI6ICJub3dfb25fdHYiLCAKICAgICJjYXRlZ29yeSI6ICIiLCAKICAgICJjaGFubmVsIjogImZpbG1vbnR2IiwgCiAgICAiZmFuYXJ0IjogIiIsIAogICAgImluZm9MYWJlbHMiOiB7fSwgCiAgICAidGh1bWJuYWlsIjogImh0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9rb2Rpb25kZW1hbmQvbWVkaWEvbWFzdGVyL3RoZW1lcy9kZWZhdWx0L3RodW1iX29uX3RoZV9haXIucG5nIiwgCiAgICAidGl0bGUiOiAiW09nZ2kgaW4gVFZdIEZpbG0gIzEiLCAKICAgICJ0b3RhbEl0ZW1zIjogMCwgCiAgICAidXJsIjogImh0dHBzOi8vd3d3LnN1cGVyZ3VpZGF0di5pdC9maWxtLWluLXR2LyIKfQ%3d%3d
2020-01-21 08:16:25.931 T:7628   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.kod/?ewogICAgImFjdGlvbiI6ICJub3dfb25fdHYiLCAKICAgICJjYXRlZ29yeSI6ICIiLCAKICAgICJjaGFubmVsIjogImZpbG1vbnR2IiwgCiAgICAiZmFuYXJ0IjogIiIsIAogICAgImluZm9MYWJlbHMiOiB7fSwgCiAgICAidGh1bWJuYWlsIjogImh0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9rb2Rpb25kZW1hbmQvbWVkaWEvbWFzdGVyL3RoZW1lcy9kZWZhdWx0L3RodW1iX29uX3RoZV9haXIucG5nIiwgCiAgICAidGl0bGUiOiAiW09nZ2kgaW4gVFZdIEZpbG0gIzEiLCAKICAgICJ0b3RhbEl0ZW1zIjogMCwgCiAgICAidXJsIjogImh0dHBzOi8vd3d3LnN1cGVyZ3VpZGF0di5pdC9maWxtLWluLXR2LyIKfQ%3d%3d) failed

**Comment by xXTimmy89Xx** [comment]
Corretto in f715e66 grazie @Alhaziel01
