### ISSUE TITLE
Nuova versione adesso in onda KoD stabile android

### ISSUE THREAD

**Issue by xXTimmy89Xx** [Stream4me/addon#222]
Dopo l'aggiornamento alla nuova versione di adesso in onda su android qualsiasi sezione tranne canali live genera errore 

2020-07-04 20:22:56.668 T:3119   ERROR: ######## ERROR #########
2020-07-04 20:22:56.668 T:3119   ERROR:     [kod.core.jsontools.load] Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kod/core/jsontools.py", line 43, in load
                                                value = json.loads(*args, **kwargs)
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/json/__init__.py", line 352, in loads
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/json/decoder.py", line 364, in decode
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                            ValueError: No JSON object could be decoded
2020-07-04 20:22:56.686 T:3119   ERROR: ######## ERROR #########
2020-07-04 20:22:56.686 T:3119   ERROR:     [kod.core.jsontools.load] ERROR STACK fromurl
2020-07-04 20:22:57.692 T:3119   ERROR: GetDirectory - Error getting
2020-07-04 20:23:01.573 T:3037   ERROR: Previous line repeats 2 times.
2020-07-04 20:23:01.573 T:3037   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
2020-07-04 20:23:01.748 T:3119   ERROR: GetDirectory - Error getting

[log282530447.log](https://github.com/kodiondemand/addon/files/4873607/log282530447.log)

**Comment by mac12m99** [comment]
Ciao,
riprova sulla beta, ho mandato un commit che potrebbe aiutare (non ne sono sicuro perchè non so di preciso di cosa si tratta)

Grazie

**Comment by Timmy89ITA** [comment]
> Ciao,
> riprova sulla beta, ho mandato un commit che potrebbe aiutare (non ne sono sicuro perchè non so di preciso di cosa si tratta)
> 
> Grazie
Confermo che ora sembra funzionare!

**Comment by xXTimmy89Xx** [comment]
> Ciao,
> riprova sulla beta, ho mandato un commit che potrebbe aiutare (non ne sono sicuro perchè non so di preciso di cosa si tratta)
> 
> Grazie

Confermo che ora sembra funzionare!

**Comment by xXTimmy89Xx** [comment]
@mac12m99 Ho notato un altro piccolo problema, quando si prova a cliccare su successivo per continuare a visualizzare i risultati dell'epg si riceve errore, l'errore si presenta solo su android.

[LOG871236371.log](https://github.com/kodiondemand/addon/files/4928293/LOG871236371.log)

**Comment by mac12m99** [comment]
Riprova ora
dc5b317ba4662d919b5e46799128296fbe21dd48

**Comment by xXTimmy89Xx** [comment]
@mac12m99 Ho notato un rallentamento generale nella reattività dell'apertura dei menu nella sezione ora in tv esempio quando si clicca su tutti o sull'apertura di un singolo canale ma sembra funzionare tutto correttamente !

[177T171.txt](https://github.com/kodiondemand/addon/files/4933452/177T171.txt)

**Comment by mac12m99** [comment]
Il metodo nuovo per adesso in onda (EPG) per sua natura è un po' più lento, di quanto tempo si tratta?

**Comment by xXTimmy89Xx** [comment]
> Il metodo nuovo per adesso in onda (EPG) per sua natura è un po' più lento, di quanto tempo si tratta?

Se per esempio se vado su in onda oggi e seleziono il genere Animazione nonostante oggi in programmazioni non ci sia nulla ci mette anche anche 2 minuti buoni per  restituirmi Nessun elemento da visualizzare o su guida per canale una volta selezionato il canale desiderato prima di vedere la programmazione ci mette il medesimo tempo se non a volte maggiore prima del fix della pagina successiva su android sembrava metterci meno tempo, comunque è un tempo accettabile.
