### ISSUE TITLE
Errore inaspettato server X videoteca con autoplay attivo

### ISSUE THREAD

**Issue by xXTimmy89Xx** [Stream4me/addon#274]
Dopo l'aggiornamento alla versione 1.6 di Kod ho riscontrato il seguente problema, quando provo ad avviare un film o un episodio di una serie da un determinato server dalla videoteca, dopo averlo stoppato e successivamente provato ad avviarlo nuovamente o selezionato l'episodio successivo dal medesimo server ricevo il seguente errore :

![screenshot000](https://user-images.githubusercontent.com/53865707/108277543-d8f74f80-7179-11eb-8013-4a232809c1df.png)

![screenshot001](https://user-images.githubusercontent.com/53865707/108602681-92853900-73a3-11eb-918f-717070e2b456.png)

Allego file log

[kodi.log](https://github.com/kodiondemand/addon/files/5999090/kodi.log)

Al momento ho usato streamtape e HDmario per ricreare il problema ma si presentava anche con altri siti di hosting e a quanto pare si presenta solo dalla videoteca.

2021-02-20 17:42:44.781 T:5892   ERROR: kod[servertools.resolve_video_urls_for_playing:326]:  ######## ERROR #########
2021-02-20 17:42:44.781 T:5892   ERROR: kod[servertools.resolve_video_urls_for_playing:326]:  Could not verify if the video exists
2021-02-20 17:42:44.781 T:5892   ERROR: kod[servertools.resolve_video_urls_for_playing:328]:  ######## ERROR #########
2021-02-20 17:42:44.781 T:5892   ERROR: kod[servertools.resolve_video_urls_for_playing:328]:  Traceback (most recent call last):
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\core\servertools.py", line 316, in resolve_video_urls_for_playing
                                                video_exists, message = server_module.test_video_exists(page_url=url)
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\servers\hdmario.py", line 16, in test_video_exists
                                                logger.debug(page.url)
                                            AttributeError: type object 'HTTPResponse' has no attribute 'url'
2021-02-20 17:42:44.781 T:5892  NOTICE: kod[servertools.resolve_video_urls_for_playing:351]:  Invoking a hdmario.get_video_url
2021-02-20 17:42:44.781 T:5892  NOTICE: kod[hdmario.get_video_url:105]:  url=
2021-02-20 17:42:44.781 T:5892   ERROR: kod[servertools.resolve_video_urls_for_playing:355]:  ######## ERROR #########
2021-02-20 17:42:44.781 T:5892   ERROR: kod[servertools.resolve_video_urls_for_playing:355]:  Error getting url in free mode
2021-02-20 17:42:44.781 T:5892   ERROR: kod[servertools.resolve_video_urls_for_playing:358]:  ######## ERROR #########
2021-02-20 17:42:44.782 T:5892   ERROR: kod[servertools.resolve_video_urls_for_playing:358]:  Traceback (most recent call last):
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\core\servertools.py", line 352, in resolve_video_urls_for_playing
                                                response = serverid.get_video_url(page_url=url, video_password=video_password)
                                              File "C:\Users\Timmy89\AppData\Roaming\Kodi\addons\plugin.video.kod\servers\hdmario.py", line 107, in get_video_url
                                                if 'unconfirmed' in page.url:
                                            AttributeError: type object 'HTTPResponse' has no attribute 'url'

**Comment by xXTimmy89Xx** [comment]
Dopo ulteriori test ho notato che il problema si presenta solo con autoplay attivo

![screenshot000](https://user-images.githubusercontent.com/53865707/109054500-3a6d7000-76de-11eb-9068-b7c15c416f4b.png)

Allego video con tutti i passaggi che ho fatto per ricreare l'errore confermo che il problema si presenta solo con l'autoplay Attivo

https://www.youtube.com/watch?v=85_uBs9r_tc

**Comment by mac12m99** [comment]
Ciao,
credo di aver finalmente capito il problema: era specifico per seriehd e si presentava solo con autoplay in quanto veniva risolto hdpass e aggiornata la lista a schermo con l'url del server, il problema è che al tentativo successivo ci riprovava con l'url già risolto e ovviamente falliva.
Risolto con 31a3eb3e0523dbe4bb4d5395abe9abdedc8a98e9, anche se sospetto ci siano altri canali che abbiano problemi simili..

**Comment by xXTimmy89Xx** [comment]
> Ciao,
> credo di aver finalmente capito il problema: era specifico per seriehd e si presentava solo con autoplay in quanto veniva risolto hdpass e aggiornata la lista a schermo con l'url del server, il problema è che al tentativo successivo ci riprovava con l'url già risolto e ovviamente falliva.
> Risolto con [31a3eb3](https://github.com/kodiondemand/addon/commit/31a3eb3e0523dbe4bb4d5395abe9abdedc8a98e9), anche se sospetto ci siano altri canali che abbiano problemi simili..

Buona sera, principalmente dai test da me effettuati il problema sembrava presentarsi sui film di Altadefinizione.click e le serie di seriehd che se non erro usano entrambi HDpass quindi il fix sembra funzionare per entrambi, come sempre grazie del fix e del lavoro svolto.
