### ISSUE TITLE
Problemi autoplay dopo commit 1949aac su android tv

### ISSUE THREAD

**Issue by xXTimmy89Xx** [Stream4me/addon#310]
Dopo l'aggiornamento con commit  1949aac l'autoplay ha smesso di funzionare completamente sui canali normali mentre  se si prova ad avviare una serie tv o un film dalla libreria di Kodi o dalla videoteca dopo un tentativo di avvio del server da errore chiedendo se si vuole mandare una segnalazione, al momento sono su Android tv Sony Kodi 19.1, grazie anticipatamente. 

2021-06-17 04:51:01.477 T:9598    ERROR <general>: kod[launcher.run:315]:  ######## ERROR #########
2021-06-17 04:51:01.478 T:9598    ERROR <general>: kod[launcher.run:315]:  Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kod/platformcode/launcher.py", line 218, in run
                                                       itemlist = getattr(channel, item.action)(item)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kod/specials/videolibrary.py", line 554, in findvideos
                                                       if autoplay.play_multi_channel(item, itemlist):  # hideserver
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kod/core/autoplay.py", line 288, in play_multi_channel
                                                       start(itemlist, item)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kod/core/autoplay.py", line 56, in start
                                                       if config.get_setting('favorites_servers_list', server=server) and server.lower() not in favorite_servers:
                                                   TypeError: argument of type 'NoneType' is not iterable

**Comment by mac12m99** [comment]
Ciao,
questo errore dovrebbe essere risolto, confermi?

**Comment by xXTimmy89Xx** [comment]
Si il problema è stato corretto con il commit ae3815e grazie come sempre del lavoro svolto.
