### ISSUE TITLE
Problema Altadefinzione Community, videoteca e streamtape su Android

### ISSUE THREAD

**Issue by xXTimmy89Xx** [Stream4me/addon#338]
Quando si prova a riprodurre una serie dalla videoteca aggiunta da altadefinizione community dal server streamtape con autoplay si riceve l'errore "Sembra che i collegamenti di streamtape non funzionino" e se si tenta di riprodurre l'episodio dal menu contestuale viene chiesto se si vuole segnalare il problema, solo in rari casi funziona tutto correttamente e i link partono

2021-08-25 15:44:18.618 T:20888    INFO <general>: kod[platformtools.set_player:1346]:  mediaurl=https://868418908.tapecontent.net/radosgw/4y4JQW9bQ3SrGA/AdbbGbO2fRlFD8Yz_1ODliYCS_RmfeRYmTWnv5cxV55EL_ma4ln-pphpLPW6raeiDQuG-UuDytSaNc5tuItagqptWxWlg3kLI0xzL_01sUF6kJehf0fRmcGuafhxhdjsB7LPQdIoehuAX1qZRTx-PswOj46XJ8vXq6BCSZMZFA84eCmGmqvN_bJnhlmHR3a2QwzntWbU16VGq6JmEhJsRdIKOBf9Toy4quKrbzgRKmh9-KdLAwuZo0FHXNe_QTb_HacXRJebxYCZPoy6yAgaaQR1RpP17Exc64gBXNpYW1-z6JwZkPil3z2UQY6Kmm3Wib0gQXzwlAs3LOcz/Carnival+Row+%5Bs1%5D+%5Be1%5D+%5B1%5D+%5Bm1080p%5D+%282019%29+%5BID256%5D.mp4.mp4
2021-08-25 15:44:18.642 T:20888   ERROR <general>: kod[launcher.run:314]:  ######## ERROR #########
2021-08-25 15:44:18.642 T:20888   ERROR <general>: kod[launcher.run:314]:  Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kod/platformcode/launcher.py", line 190, in run
                                                       platformtools.play_video(item)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kod/platformcode/platformtools.py", line 989, in play_video
                                                       if not play():
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kod/platformcode/platformtools.py", line 986, in play
                                                       set_player(item, xlistitem, mediaurl, view, strm)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kod/platformcode/platformtools.py", line 1351, in set_player
                                                       item.played_time = resume_playback(get_played_time(item))
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kod/platformcode/platformtools.py", line 1507, in resume_playback
                                                       if played_time and played_time > 30:
                                                   TypeError: '>' not supported between instances of 'dict' and 'int'

Aggiungendo la stessa serie da Altadefinizione.click i link di streamtape invece funzionano senza problemi.

**Comment by xXTimmy89Xx** [comment]
Corretto con commit 7bb4c5b
